import "./globals.css";
import { Cormorant, DM_Sans } from "next/font/google";
import Link from "next/link";

import { setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { CartProvider } from "@/context/cartContext";

import Footer from "../components/footer/footer";

const cormorant = Cormorant({
  subsets: ["latin"], // ou ['latin-ext'] si besoin
  weight: ["400", "500", "600", "700"], // choisis tes graisses
  variable: "--font-cormorant", // optionnel pour l'utiliser en CSS
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={dmSans.className}>
        {/* On enveloppe tout dans NextIntl + CartProvider */}
        <NextIntlClientProvider>
          <CartProvider>
            {children}
            <Footer />
            {/* <p style={{ textAlign: "center", color: "#555" }}>
              Made with love by{" "}
              <Link href="https://www.arthurbarraud.me">
                Arthur Barraud
              </Link>{" "}
            </p> */}
          </CartProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
